name=OptimizedGPIO
version=1.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Optimized General-Purpose IO (GPIO) Library
paragraph=Over 10x faster than digitalRead() and digitalWrite(). Works on most platforms (STM32, SAMD, AVR, ESP32 and ESP8266).
category=Signal Input/Output
url=https://github.com/mumanchu/OptimizedGPIO
architectures=*
includes=OptimizedGPIO.h
